{
 "title": "wrk2 Summary",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rps",
    "label": "Requested RPS",
    "query": "wrk2_benchmark_summary_latency_ms"
   },
   { "name": "exclude", "label": "Exclude", "query": "No exclusion,run" },
   {
    "name": "exclude_runs",
    "label": "Runs to exclude",
    "query": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<h1><center>Benchmark latency summary</center></h1>\n<hr>\n<h3><center>Bare Metal, Linkerd, and Istio compared</center></h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "content": "<br />\n<center><b>0.5 percentile</b></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "content": "<br />\n<center><b>0.75 percentile</b></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "content": "<br />\n<center><b>0.9 percentile</b></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "content": "<br />\n<center><b>0.99 percentile</b></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "content": "<br />\n<center><b>0.999 percentile</b></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "content": "<br />\n<center><b>0.9999 percentile</b></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "content": "<br />\n<center><b>0.99999 percentile</b></center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "content": "<br />\n<center><b>1.0 percentile</b></center>"
  },
  {
   "title": "bare",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.5\",job=\"bare-metal\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "linkerd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 1, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.5\",job=\"svcmesh-linkerd\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "istio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 2, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.5\",job=\"svcmesh-istio\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "bare",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 3, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.75\",job=\"bare-metal\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "linkerd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.75\",job=\"svcmesh-linkerd\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "istio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 5, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.75\",job=\"svcmesh-istio\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "bare",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9\",job=\"bare-metal\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "linkerd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 7, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9\",job=\"svcmesh-linkerd\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "istio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9\",job=\"svcmesh-istio\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "bare",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 9, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99\",job=\"bare-metal\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "linkerd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 10, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99\",job=\"svcmesh-linkerd\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "istio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 11, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99\",job=\"svcmesh-istio\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "bare",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.999\",job=\"bare-metal\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "linkerd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 13, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.999\",job=\"svcmesh-linkerd\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "istio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 14, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.999\",job=\"svcmesh-istio\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "bare",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9999\",job=\"bare-metal\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "linkerd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9999\",job=\"svcmesh-linkerd\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "istio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 17, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9999\",job=\"svcmesh-istio\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "bare",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99999\",job=\"bare-metal\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "linkerd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 19, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99999\",job=\"svcmesh-linkerd\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "istio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 20, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99999\",job=\"svcmesh-istio\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "bare",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 21, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"1.0\",job=\"bare-metal\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "linkerd",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 22, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"1.0\",job=\"svcmesh-linkerd\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "istio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 1, "x": 23, "y": 5 },
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"1.0\",job=\"svcmesh-istio\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
   "content": "<hr>\n<h3><center>Bare Metal latency percentiles</center>"
  },
  {
   "title": "0.5 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.5\",job=\"bare-metal\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.75 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 2, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.75\",job=\"bare-metal\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.9 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9\",job=\"bare-metal\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.99 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99\",job=\"bare-metal\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.999\",job=\"bare-metal\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.9999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 10, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9999\",job=\"bare-metal\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.99999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99999\",job=\"bare-metal\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "1.0 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"1.0\",job=\"bare-metal\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "Peak latencies (1.0 percentile)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "max(wrk2_benchmark_summary_latency_ms{job=\"bare-metal\",requested_rps=\"$rps\", p=\"1.0\",source_run!~\"$exclude_runs\"}) by (instance,start,end,source_run,value)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 },
   "content": "<hr>\n<h3><center>Linkerd latency percentiles</center>"
  },
  {
   "title": "0.5 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.5\",job=\"svcmesh-linkerd\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.75 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 2, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.75\",job=\"svcmesh-linkerd\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.9 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 4, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9\",job=\"svcmesh-linkerd\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.99 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99\",job=\"svcmesh-linkerd\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.999\",job=\"svcmesh-linkerd\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.9999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 10, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9999\",job=\"svcmesh-linkerd\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.99999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99999\",job=\"svcmesh-linkerd\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "1.0 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 14, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"1.0\",job=\"svcmesh-linkerd\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "Peak latencies (1.0 percentile)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "max(wrk2_benchmark_summary_latency_ms{job=\"svcmesh-linkerd\",requested_rps=\"$rps\", p=\"1.0\",source_run!~\"$exclude_runs\"}) by (instance,start,end,source_run,value)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
   "content": "<hr>\n<h3><center>Istio latency percentiles</center>"
  },
  {
   "title": "0.5 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.5\",job=\"svcmesh-istio\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.75 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 2, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.75\",job=\"svcmesh-istio\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.9 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 4, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9\",job=\"svcmesh-istio\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.99 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99\",job=\"svcmesh-istio\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.999\",job=\"svcmesh-istio\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.9999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 10, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.9999\",job=\"svcmesh-istio\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "0.99999 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"0.99999\",job=\"svcmesh-istio\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "1.0 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 2, "x": 14, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_summary_latency_ms{requested_rps=\"$rps\",p=\"1.0\",job=\"svcmesh-istio\",source_run!~\"$exclude_runs\"}",
     "legendFormat": "Run {{source_run}}"
    }
   ]
  },
  {
   "title": "Peak latencies (1.0 percentile)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "expr": "max(wrk2_benchmark_summary_latency_ms{job=\"svcmesh-istio\",requested_rps=\"$rps\", p=\"1.0\",source_run!~\"$exclude_runs\"}) by (instance,start,end,source_run,value)"
    }
   ]
  }
 ]
}