{
 "title": "wrk2 benchmark",
 "time": { "from": "2022-04-13T14:15:00.000Z", "to": "2022-04-13T14:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "job", "label": "Benchmark job", "query": { "query": "wrk2_benchmark_progress" } },
   {
    "name": "instance",
    "label": "Target application",
    "query": {
     "query": "wrk2_benchmark_progress{job=\"$job\"}"
    }
   },
   {
    "name": "run",
    "label": "Benchmark run",
    "query": {
     "query": "wrk2_benchmark_progress{job=\"$job\",instance=\"$instance\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_progress{instance=\"$instance\",run=\"$run\",job=\"$job\",status=\"init\"}",
     "legendFormat": "{{job}}: {{instance}} {{run}} "
    }
   ]
  },
  {
   "title": "Benchmark duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_duration{instance=\"$instance\",run=\"$run\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Progress",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_progress{instance=\"$instance\",run=\"$run\",job=\"$job\",status=~\"(init|run)\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Overall RPS (average and current)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(wrk2_benchmark_average_rps{instance=\"$instance\",run=\"$run\",job=\"$job\"})",
     "legendFormat": "Average RPS"
    },
    {
     "expr": "sum(wrk2_benchmark_current_rps{instance=\"$instance\",run=\"$run\",job=\"$job\"})",
     "legendFormat": "Current RPS"
    }
   ]
  },
  {
   "title": "Current RPS, per thread",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_current_rps{instance=\"$instance\",run=\"$run\",job=\"$job\"}",
     "legendFormat": "{{label}}{{thread}}"
    }
   ]
  },
  {
   "title": "Requested RPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_progress{instance=\"$instance\",run=\"$run\",job=\"$job\",status=\"init\"}",
     "legendFormat": "{{rps}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wrk2_benchmark_average_rps{instance=\"$instance\",run=\"$run\",job=\"$job\"})",
     "legendFormat": "Average RPS"
    },
    {
     "expr": "sum(wrk2_benchmark_current_rps{instance=\"$instance\",run=\"$run\",job=\"$job\"})",
     "legendFormat": "Current RPS"
    }
   ]
  },
  {
   "title": "Average RPS, per thread",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wrk2_benchmark_average_rps{instance=\"$instance\",run=\"$run\",job=\"$job\"}",
     "legendFormat": "{{label}}{{thread}}"
    }
   ]
  },
  {
   "title": "Thread count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_thread_count{instance=\"$instance\",run=\"$run\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Requests sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wrk2_benchmark_requests{instance=\"$instance\",run=\"$run\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Responses received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wrk2_benchmark_responses{instance=\"$instance\",run=\"$run\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Sidecar Memory usage - Load generator ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container!~\"POD\", namespace=~\"benchmark\", container=~\".*-proxy\",container!=\"\"}",
     "legendFormat": "{{container}} Memory"
    }
   ]
  },
  {
   "title": "Sidecar Memory usage - applications (max. across all sidecars)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{container!~\"POD\", namespace=~\"emojivoto.*\", container=~\"(linkerd|istio)-proxy\",container!=\"\"})  by (container)",
     "legendFormat": "{{container}} Memory"
    }
   ]
  },
  {
   "title": "Memory usage - Service mesh control plane",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!~\"POD\", namespace=~\"linkerd\", container!~\".*-proxy\",container!=\"\"})",
     "legendFormat": "Linkerd total Memory"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container!~\"POD\", namespace=~\"(istio-.*)\", container!~\".*-proxy\",container!=\"\"})",
     "legendFormat": "Istio total Memory"
    }
   ]
  },
  {
   "title": "Sidecar CPU usage - Load generator ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{namespace=~\"benchmark\", container=~\".*-proxy\",container!=\"\"}",
     "legendFormat": "{{container}} CPU seconds"
    }
   ]
  },
  {
   "title": "Sidecar CPU usage  - applications (max. across all sidecars)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(container_cpu_usage_seconds_total{namespace=~\"$instance.*\", container=~\"(linkerd|istio)-proxy\",container!=\"\"}) by (container)",
     "legendFormat": "{{container}} CPU seconds"
    }
   ]
  },
  {
   "title": "CPU utilisation - Service mesh control plane",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_cpu_usage_seconds_total{namespace=~\"linkerd\", container!~\".*-proxy\",container!=\"\"})",
     "legendFormat": "Linkerd total CPU seconds"
    },
    {
     "expr": "sum(container_cpu_usage_seconds_total{namespace=~\"istio-.*\", container!~\".*-proxy\",container!=\"\"})",
     "legendFormat": "Istio total CPU seconds"
    }
   ]
  },
  {
   "title": "Application CPU consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{namespace=~\"$instance.*\", container!=\"POD\"}",
     "legendFormat": "{{container}}-{{namespace}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "<hr>\n<center><h5> Benchmark results (updated after a benchmark run has concluded.)</h5></center>"
   }
  },
  {
   "title": "Transport Errors",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 1, "y": 33 },
   "targets": [
    {
     "expr": "wrk2_benchmark_socket_errors{instance=\"$instance\",run=\"$run\",job=\"$job\"}",
     "legendFormat": "Socket {{t}}"
    },
    {
     "expr": "wrk2_benchmark_http_errors{instance=\"$instance\",run=\"$run\",job=\"$job\"}",
     "legendFormat": "HTTP ret != 200"
    },
    {
     "expr": "wrk2_benchmark_requests_timed_out{instance=\"$instance\",run=\"$run\",job=\"$job\"}",
     "legendFormat": "HTTP timeout"
    }
   ]
  },
  {
   "title": "Avg. TCP reconnects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wrk2_benchmark_run_average_tcp_reconnect_rate{instance=\"$instance\",run=\"$run\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Requests sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_run_requests{instance=\"$instance\",run=\"$run\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Load generator threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_run_thread_count{instance=\"$instance\",run=\"$run\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Requested RPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_run_requested_rps{instance=\"$instance\",run=\"$run\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Effective RPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_run_rps{instance=\"$instance\",run=\"$run\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Total bytes read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_bytes_read{instance=\"$instance\",run=\"$run\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "started",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_run_runtime{instance=\"$instance\",run=\"$run\",job=\"$job\",kind=\"start\"} * 1000"
    }
   ]
  },
  {
   "title": "concluded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_run_runtime{instance=\"$instance\",run=\"$run\",job=\"$job\",kind=\"end\"} * 1000"
    }
   ]
  },
  {
   "title": "length",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_run_runtime{instance=\"$instance\",run=\"$run\",job=\"$job\",kind=\"duration\"}"
    }
   ]
  },
  {
   "title": "URL call counts",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "wrk2_benchmark_url_call_count{instance=\"$instance\",run=\"$run\",job=\"$job\"}",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Latency  percentile histogram (milliseconds)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 15, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_latency_ms{instance=\"$instance\",run=\"$run\",job=\"$job\"}",
     "legendFormat": "{{p}} percentile"
    }
   ]
  },
  {
   "title": "Detailed latency  percentile histogram (milliseconds)",
   "type": "bargauge",
   "gridPos": { "h": 48, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wrk2_benchmark_latency_detailed_ms{instance=\"$instance\",run=\"$run\",job=\"$job\"}",
     "legendFormat": " {{p}}"
    }
   ]
  }
 ]
}